SELECT
    F.AUTHOR_ID,
    A.AUTHOR_NAME,
    F.CATEGORY,
    F.TOTAL_SALES
FROM (SELECT
        A.AUTHOR_ID,
        B.CATEGORY,
        SUM(S.SALES * B.PRICE) AS TOTAL_SALES
      FROM BOOK_SALES S
        JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
        JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
      WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
      GROUP BY A.AUTHOR_ID, B.CATEGORY
) AS F
    JOIN AUTHOR A ON F.AUTHOR_ID = A.AUTHOR_ID
ORDER BY F.AUTHOR_ID ASC, F.CATEGORY DESC;