WITH 
    FIRST_ECOLI AS (
        SELECT ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
    ), SECOND_ECOLI AS(
        SELECT E.ID
        FROM ECOLI_DATA E
        JOIN FIRST_ECOLI F ON E.PARENT_ID = F.ID
    )
    
SELECT E.ID
FROM ECOLI_DATA E
JOIN SECOND_ECOLI S ON E.PARENT_ID = S.ID
ORDER BY E.ID ASC;