-- 코드를 입력하세요

SELECT T.YEAR, T.MONTH, T.GENDER, COUNT(T.USER_ID) AS USERS
FROM (
    SELECT DISTINCT
           TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR,
           TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) AS MONTH,
           U.GENDER AS GENDER,
           S.USER_ID
    FROM ONLINE_SALE S
    JOIN USER_INFO U ON S.USER_ID = U.USER_ID
    WHERE NOT U.GENDER IS NULL
) T
GROUP BY T.YEAR,T.MONTH,T.GENDER
ORDER BY T.YEAR ASC, T.MONTH ASC, T.GENDER ASC;