SELECT A.CAR_ID, 
       A.CAR_TYPE, 
       ((A.DAILY_FEE * 30) * ((100 - B.DISCOUNT_RATE) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON A.CAR_TYPE = B.CAR_TYPE
WHERE A.CAR_TYPE IN ('SUV','세단')
    AND B.DURATION_TYPE = '30일 이상'
    AND A.CAR_ID NOT IN (
        SELECT C.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
        WHERE TO_CHAR(C.END_DATE, 'YYYYMMDD') >= '20221101'
    )
    AND ((A.DAILY_FEE * 30) * ((100 - B.DISCOUNT_RATE) / 100)) >= 500000
    AND ((A.DAILY_FEE * 30) * ((100 - B.DISCOUNT_RATE) / 100)) < 2000000
ORDER BY 3 DESC, 2, 1 DESC;