SELECT
    RI.FOOD_TYPE,
    RI.REST_ID,
    RI.REST_NAME,
    RI.FAVORITES
FROM REST_INFO RI
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS BRI
ON RI.FOOD_TYPE = BRI.FOOD_TYPE AND RI.FAVORITES = BRI.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC;