# 2025-08-03
SELECT
    I.FOOD_TYPE,
    I.REST_ID,
    I.REST_NAME,
    I.FAVORITES
FROM REST_INFO I
JOIN (
    SELECT
        FOOD_TYPE,
        MAX(FAVORITES) MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) MI ON I.FOOD_TYPE = MI.FOOD_TYPE AND I.FAVORITES = MI.MAX_FAVORITES
ORDER BY I.FOOD_TYPE DESC;