-- 코드를 입력하세요
SELECT
    H.CAR_ID,
    D.DUR
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN (
    SELECT
        CAR_ID,
        ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS DUR
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING DUR >= 7
) D ON H.CAR_ID = D.CAR_ID
GROUP BY H.CAR_ID
ORDER BY D.DUR DESC, CAR_ID DESC;
