SELECT
    C.FISH_COUNT,
    N.FISH_NAME
FROM FISH_NAME_INFO N
LEFT JOIN (
    SELECT
        FISH_TYPE,
        COUNT(ID) AS FISH_COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE) C ON C.FISH_TYPE = N.FISH_TYPE
ORDER BY C.FISH_COUNT DESC;