WITH
USERS AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE EXTRACT(YEAR FROM JOINED) = 2021
),
TOTAL_USER AS (
    SELECT COUNT(1) AS TOTAL
    FROM USERS
),
GROUPING AS (
    SELECT EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR,
           EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH,
           O.USER_ID
    FROM ONLINE_SALE O
    JOIN USERS U ON O.USER_ID = U.USER_ID
    GROUP BY EXTRACT(YEAR FROM O.SALES_DATE),
             EXTRACT(MONTH FROM O.SALES_DATE),
             O.USER_ID
)

SELECT G.YEAR, G.MONTH,
       COUNT(G.USER_ID) AS PUCHASED_USERS,
       ROUND(COUNT(G.USER_ID) / (SELECT TOTAL FROM TOTAL_USER), 1) AS PUCHASED_RATIO
FROM GROUPING G
GROUP BY G.YEAR, G.MONTH
ORDER BY 1,2;