-- 코드를 입력하세요
SELECT O.PRODUCT_ID, P.PRODUCT_NAME, (O.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN TO_DATE('2022-05-01', 'YYYY-MM-DD') AND TO_DATE('2022-05-31', 'YYYY-MM-DD')
    GROUP BY PRODUCT_ID
) O
JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY (O.AMOUNT * P.PRICE) DESC, O.PRODUCT_ID ASC;