WITH TMP AS (
    SELECT H.HISTORY_ID, 
           C.CAR_TYPE,
           H.START_DATE,
           H.END_DATE,
           C.DAILY_FEE,
           (CASE WHEN (H.END_DATE - H.START_DATE) + 1 < 7 THEN NULL
                WHEN (H.END_DATE - H.START_DATE) + 1 < 30 THEN '7일 이상'
                WHEN (H.END_DATE - H.START_DATE) + 1 < 90 THEN '30일 이상'
                ELSE '90일 이상' END) AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT T.HISTORY_ID,
       TRUNC((T.END_DATE - T.START_DATE + 1) * DAILY_FEE * (1 - NVL(DISCOUNT_RATE, 0) / 100)) AS FEE
FROM TMP T
    LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
        ON T.CAR_TYPE = P.CAR_TYPE 
        AND T.DURATION_TYPE = P.DURATION_TYPE
ORDER BY 2 DESC, 1 DESC;