WITH VIP_USER AS (
    SELECT
        U.USER_ID,
        SUM(B.PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD B
    JOIN USED_GOODS_USER U
        ON U.USER_ID = B.WRITER_ID
    WHERE B.STATUS = 'DONE'
    GROUP BY U.USER_ID
    HAVING SUM(B.PRICE) >= 700000
)

SELECT
    V.USER_ID,
    U.NICKNAME,
    V.TOTAL_SALES
FROM VIP_USER V
LEFT JOIN USED_GOODS_USER U ON V.USER_ID = U.USER_ID
ORDER BY V.TOTAL_SALES ASC;