SELECT
    U.USER_ID,
    U.NICKNAME,
    FU.TOTAL_SALES
FROM USED_GOODS_USER U
JOIN (
    SELECT
        B.WRITER_ID,
        SUM(B.PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD B
    WHERE STATUS = 'DONE'
    GROUP BY B.WRITER_ID
    HAVING SUM(B.PRICE) >= 700000
) AS FU
ON U.USER_ID = FU.WRITER_ID
ORDER BY TOTAL_SALES ASC;