-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME,
       (CITY || ' ' || U.STREET_ADDRESS1 || ' ' || U.STREET_ADDRESS2) AS 전체주소,
       REGEXP_REPLACE(U.TLNO, '(.{3})(.+)(.{4})', '\1-\2-\3') AS 전화번호
FROM USED_GOODS_USER U
JOIN (
    SELECT B.WRITER_ID, COUNT(*)
    FROM USED_GOODS_BOARD B
    GROUP BY B.WRITER_ID
    HAVING COUNT(*) >= 3
) T ON U.USER_ID = T.WRITER_ID
ORDER BY U.USER_ID DESC;