WITH UPGRADED_FROM_RARE AS (
    SELECT
        T.ITEM_ID
    FROM ITEM_INFO I
    JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE I.RARITY = 'RARE'
)

SELECT
    I.ITEM_ID,
    I.ITEM_NAME,
    I.RARITY
FROM ITEM_INFO I
RIGHT JOIN UPGRADED_FROM_RARE U ON I.ITEM_ID = U.ITEM_ID
ORDER BY I.ITEM_ID DESC;