SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    ABS(E.SIZE_OF_COLONY - SUB.MAX_SIZE) AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
JOIN (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) SUB ON YEAR(E.DIFFERENTIATION_DATE) = SUB.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;