-- 코드를 입력하세요
SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES P
JOIN (
    SELECT P2.HOST_ID, COUNT(P2.HOST_ID)
    FROM PLACES P2
    GROUP BY P2.HOST_ID
    HAVING COUNT(P2.HOST_ID) >= 2
) T ON P.HOST_ID = T.HOST_ID
ORDER BY P.ID;