-- 코드를 입력하세요
SELECT
    I.FLAVOR
FROM ICECREAM_INFO I
JOIN FIRST_HALF F
    ON I.FLAVOR = F.FLAVOR
WHERE I.INGREDIENT_TYPE = 'fruit_based'
GROUP BY I.FLAVOR
HAVING SUM(F.TOTAL_ORDER) > 3000
ORDER BY SUM(F.TOTAL_ORDER) DESC;