-- 코드를 입력하세요
SELECT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '세단'
    AND START_DATE BETWEEN TO_DATE(20221001, 'YYYY-MM-DD') AND TO_DATE(20221031, 'YYYY-MM-DD')
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC;