WITH GRADED_EMP AS (
    SELECT
        G.EMP_NO,
        SUM(G.SCORE) AS TOTAL_SCORE,
        RANK() OVER (ORDER BY SUM(G.SCORE) DESC) AS SCORE_RANK
    FROM HR_GRADE G
    WHERE G.YEAR = 2022
    GROUP BY G.EMP_NO
)

SELECT
    GE.TOTAL_SCORE AS SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM GRADED_EMP GE
JOIN HR_EMPLOYEES E ON GE.EMP_NO = E.EMP_NO
WHERE GE.SCORE_RANK = 1;