# 2025-08-04
SELECT
    D.DEPT_ID,
    D.DEPT_NAME_EN,
    ROUND(E.AVG_SAL) AS AVG_SAL
FROM HR_DEPARTMENT D
JOIN (
    SELECT
        DEPT_ID,
        AVG(SAL) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) E ON D.DEPT_ID = E.DEPT_ID
GROUP BY D.DEPT_ID
ORDER BY E.AVG_SAL DESC;