SELECT
    DS.DEPT_ID,
    D.DEPT_NAME_EN,
    DS.AVG_SAL
FROM (SELECT
        DEPT_ID,
        ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID) DS
JOIN HR_DEPARTMENT D ON DS.DEPT_ID = D.DEPT_ID
ORDER BY DS.AVG_SAL DESC;