-- 코드를 입력하세요
SELECT T.FLAVOR
FROM (
    SELECT F.FLAVOR, SUM(F.TOTAL_ORDER + J.TOTAL_ORDER)
    FROM FIRST_HALF F
    JOIN JULY J ON F.FLAVOR = J.FLAVOR
    GROUP BY F.FLAVOR
    ORDER BY SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
    FETCH FIRST 3 ROWS ONLY
) T