-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B
INNER JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE BETWEEN TO_DATE('20220101', 'YYYY-MM-DD') AND TO_DATE('20220131', 'YYYY-MM-DD')
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;