# 2025-07-25
WITH MAX_PRODUCT AS (
    SELECT
        CATEGORY,
        MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT
    P.CATEGORY,
    P.PRICE AS MAX_PRICE,
    P.PRODUCT_NAME
FROM FOOD_PRODUCT P
JOIN MAX_PRODUCT MP ON P.PRICE = MP.MAX_PRICE
    AND P.CATEGORY = MP.CATEGORY
ORDER BY P.PRICE DESC;