SELECT
    MP.CATEGORY,
    MP.MAX_PRICE,
    P.PRODUCT_NAME
FROM FOOD_PRODUCT P
JOIN (
    SELECT
        CATEGORY,
        MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) MP ON P.PRICE = MP.MAX_PRICE AND P.CATEGORY = MP.CATEGORY
WHERE P.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MP.MAX_PRICE DESC;